"""Shared result/config types for Tier 1.

Nothing in `tier1_compute` may import an LLM client, and nothing here
accepts a natural-language explanation as an input. A Tier 1 result is a
verdict plus a machine-readable reason code; turning that into prose is
strictly the job of `backend/rag/phrasing.py`, downstream and after the
fact. See the hard rule in CLAUDE.md.
"""

from __future__ import annotations

import enum
import math
from dataclasses import dataclass, field
from typing import Any


class Outcome(str, enum.Enum):
    #: Reported result is self-consistent with the student's own raw data.
    PASS = "pass"
    #: Inconsistent, and a deterministic signature explains why.
    FAIL_WITH_SIGNATURE = "fail_with_signature"
    #: Inconsistent, but no signature matched -- flows on to Tier 2.
    FAIL_NO_SIGNATURE = "fail_no_signature"
    #: Input could not be checked at all (missing/instructurally bad data).
    INVALID = "invalid"
    #: This experiment has no deterministic check by design (Exp 7/8).
    NOT_APPLICABLE = "not_applicable"


class Action(str, enum.Enum):
    """What the student should do next. Mapped from the outcome, never
    chosen by an LLM."""

    NONE = "none"
    FIX_IN_PLACE = "fix_in_place"
    REDO_STEP = "redo_step"
    RESTART = "restart"
    AWAIT_REVIEW = "await_review"


@dataclass(frozen=True)
class Tolerance:
    """Acceptance band for a comparison.

    Both bounds are optional; a value passes if it is within *either*
    band that is configured. Per-experiment values must come from the
    course manual, not from a guess.
    """

    abs_tol: float | None = None
    rel_tol: float | None = None

    def __post_init__(self) -> None:
        if self.abs_tol is None and self.rel_tol is None:
            raise ValueError("Tolerance needs at least one of abs_tol / rel_tol")
        for name in ("abs_tol", "rel_tol"):
            v = getattr(self, name)
            if v is not None and v < 0:
                raise ValueError(f"{name} must be non-negative")

    def matches(self, expected: float, reported: float) -> bool:
        if not (math.isfinite(expected) and math.isfinite(reported)):
            return False
        delta = abs(expected - reported)
        if self.abs_tol is not None and delta <= self.abs_tol:
            return True
        if self.rel_tol is not None:
            denom = abs(expected)
            if denom == 0.0:
                return delta == 0.0
            if delta / denom <= self.rel_tol:
                return True
        return False

    def describe(self) -> str:
        parts = []
        if self.abs_tol is not None:
            parts.append(f"+/-{self.abs_tol:g} absolute")
        if self.rel_tol is not None:
            parts.append(f"+/-{self.rel_tol * 100:g}% relative")
        return " or ".join(parts)


@dataclass(frozen=True)
class SignatureHit:
    """A matched deviation signature."""

    code: str
    #: Short, student-independent statement of the detected pattern. This
    #: is a fact for the phrasing layer to render -- not the final prose.
    detail: str
    evidence: dict[str, Any] = field(default_factory=dict)


@dataclass
class Tier1Result:
    outcome: Outcome
    expected_value: float | None = None
    reported_value: float | None = None
    signature: SignatureHit | None = None
    #: Structured facts the phrasing layer may render. Never free prose
    #: generated by a model.
    detail: dict[str, Any] = field(default_factory=dict)
    #: Populated for INVALID outcomes.
    errors: list[str] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return self.outcome is Outcome.PASS

    @property
    def signature_code(self) -> str | None:
        return self.signature.code if self.signature else None

    def action(self) -> Action:
        """Deterministic outcome -> remediation mapping."""
        if self.outcome is Outcome.PASS:
            return Action.NONE
        if self.outcome is Outcome.INVALID:
            return Action.FIX_IN_PLACE
        if self.outcome is Outcome.NOT_APPLICABLE:
            return Action.AWAIT_REVIEW
        if self.signature is not None:
            return _SIGNATURE_ACTIONS.get(self.signature.code, Action.REDO_STEP)
        return Action.AWAIT_REVIEW


#: Which remediation each signature implies. An arithmetic/transcription
#: slip is fixable at the desk; a data-quality problem means re-running
#: the measurement; a procedural error means starting the run over.
_SIGNATURE_ACTIONS: dict[str, Action] = {
    "arithmetic_slip": Action.FIX_IN_PLACE,
    "unit_scale_error": Action.FIX_IN_PLACE,
    "sign_flip": Action.FIX_IN_PLACE,
    "transposed_inputs": Action.FIX_IN_PLACE,
    "rounding_drift": Action.FIX_IN_PLACE,
    "used_wrong_formula_branch": Action.FIX_IN_PLACE,
    "coarse_increments": Action.REDO_STEP,
    "unresolved_peak": Action.REDO_STEP,
    "non_monotonic_data": Action.REDO_STEP,
    "poor_linear_fit": Action.REDO_STEP,
    "insufficient_points": Action.REDO_STEP,
    "extrapolated_beyond_standards": Action.REDO_STEP,
    "endpoint_outside_data_range": Action.REDO_STEP,
    "no_detectable_endpoint": Action.RESTART,
    "flat_response": Action.RESTART,
    "standards_not_bracketing": Action.RESTART,
}


@dataclass(frozen=True)
class StepSpec:
    """One procedural step in Socratic mode.

    `compute` derives the step's expected value from the student's own
    prior data. `hints` is the fixed three-rung ladder: vague, specific,
    then naming the likely issue. No rung contains the numeric answer --
    `tests/test_socratic_refusal.py` asserts that structurally.
    """

    index: int
    key: str
    prompt: str
    #: Input keys this step needs from the student's own data.
    requires: tuple[str, ...] = ()
    tolerance: Tolerance | None = None
    hints: tuple[str, str, str] = ("", "", "")
    #: True for the step whose value is the experiment's final answer.
    is_final: bool = False
