"""user role override and reg no

Revision ID: 0221e365797d
Revises: efab60770028
Create Date: 2026-09-16 23:36:08.115910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0221e365797d'
down_revision: Union[str, None] = 'efab60770028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reg_no', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('role_override', sa.Enum('STUDENT', 'FACULTY', 'ADMIN', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_override')
    op.drop_column('users', 'reg_no')
    # ### end Alembic commands ###
