"""add onboarded flag to users

Revision ID: b095d8d1a05a
Revises: a1b2c3d4e5f6
Create Date: 2026-09-17 11:50:54.274649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b095d8d1a05a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so this is safe on a table with existing rows (real
    # deployments, not just a fresh dev DB) -- existing users are treated
    # as not-yet-onboarded under the new flag, same as the model default.
    op.add_column(
        'users',
        sa.Column('onboarded', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded')
    # ### end Alembic commands ###
