"""baseline schema

Revision ID: efab60770028
Revises: 
Create Date: 2026-09-16 18:54:10.445815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efab60770028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('classroom_id', sa.String(length=36), nullable=True),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_class_session_id'), 'audit_log', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_audit_log_classroom_id'), 'audit_log', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_event'), 'audit_log', ['event'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('student_join_code', sa.String(length=64), nullable=False),
    sa.Column('faculty_join_code', sa.String(length=64), nullable=False),
    sa.Column('join_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_faculty_join_code'), 'classrooms', ['faculty_join_code'], unique=True)
    op.create_index(op.f('ix_classrooms_student_join_code'), 'classrooms', ['student_join_code'], unique=True)
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', 'key', name='uq_idempotency')
    )
    op.create_index('ix_idem_lookup', 'idempotency_records', ['user_id', 'scope', 'key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', 'ADMIN', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('class_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by', sa.String(length=36), nullable=False),
    sa.Column('ended_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['ended_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_class_sessions_active_lookup', 'class_sessions', ['classroom_id', 'status'], unique=False)
    op.create_index(op.f('ix_class_sessions_classroom_id'), 'class_sessions', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_experiment_id'), 'class_sessions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_status'), 'class_sessions', ['status'], unique=False)
    op.create_index('uq_one_active_session_per_classroom', 'class_sessions', ['classroom_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_table('classroom_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', name='classroomrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'user_id', 'role', name='uq_membership')
    )
    op.create_index(op.f('ix_classroom_memberships_active'), 'classroom_memberships', ['active'], unique=False)
    op.create_index(op.f('ix_classroom_memberships_classroom_id'), 'classroom_memberships', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_memberships_role'), 'classroom_memberships', ['role'], unique=False)
    op.create_index(op.f('ix_classroom_memberships_user_id'), 'classroom_memberships', ['user_id'], unique=False)
    op.create_table('socratic_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.Enum('STUDENT', 'FACULTY_TEST', 'ADMIN_TEST', name='actortype'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('student_data', sa.JSON(), nullable=False),
    sa.Column('all_steps_complete', sa.Boolean(), nullable=False),
    sa.Column('revealed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socratic_sessions_actor_type'), 'socratic_sessions', ['actor_type'], unique=False)
    op.create_index(op.f('ix_socratic_sessions_class_session_id'), 'socratic_sessions', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_socratic_sessions_classroom_id'), 'socratic_sessions', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_socratic_sessions_experiment_id'), 'socratic_sessions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_socratic_sessions_student_id'), 'socratic_sessions', ['student_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.Enum('STUDENT', 'FACULTY_TEST', 'ADMIN_TEST', name='actortype'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('reported_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_actor_type'), 'submissions', ['actor_type'], unique=False)
    op.create_index(op.f('ix_submissions_class_session_id'), 'submissions', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_submissions_classroom_id'), 'submissions', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_submissions_experiment_id'), 'submissions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('summary_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_jobs_class_session_id'), 'summary_jobs', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_summary_jobs_classroom_id'), 'summary_jobs', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_summary_jobs_status'), 'summary_jobs', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('SOCRATIC', 'QA', name='chatmessagekind'), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.Enum('STUDENT', 'FACULTY_TEST', 'ADMIN_TEST', name='actortype'), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['socratic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_actor_type'), 'chat_messages', ['actor_type'], unique=False)
    op.create_index(op.f('ix_chat_messages_class_session_id'), 'chat_messages', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_classroom_id'), 'chat_messages', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_experiment_id'), 'chat_messages', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_kind'), 'chat_messages', ['kind'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_student_id'), 'chat_messages', ['student_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'ESCALATED', 'INVALID', name='diagnosisstatus'), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('signature_code', sa.String(length=64), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('reported_value', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('action', sa.Enum('NONE', 'FIX_IN_PLACE', 'REDO_STEP', 'RESTART', 'AWAIT_REVIEW', name='remedialaction'), nullable=False),
    sa.Column('phrased_text', sa.Text(), nullable=False),
    sa.Column('phrasing_source', sa.String(length=32), nullable=False),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_class_session_id'), 'diagnoses', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_classroom_id'), 'diagnoses', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_status'), 'diagnoses', ['status'], unique=False)
    op.create_index(op.f('ix_diagnoses_student_id'), 'diagnoses', ['student_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_submission_id'), 'diagnoses', ['submission_id'], unique=True)
    op.create_index(op.f('ix_diagnoses_tier'), 'diagnoses', ['tier'], unique=False)
    op.create_table('socratic_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('submitted_value', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['socratic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socratic_attempts_session_id'), 'socratic_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_socratic_attempts_student_id'), 'socratic_attempts', ['student_id'], unique=False)
    op.create_table('student_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['summary_jobs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_session_id', name='uq_summary_session')
    )
    op.create_index(op.f('ix_student_summaries_class_session_id'), 'student_summaries', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_student_summaries_classroom_id'), 'student_summaries', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_student_summaries_experiment_id'), 'student_summaries', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_student_summaries_student_id'), 'student_summaries', ['student_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_class_session_id'), 'escalations', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_escalations_classroom_id'), 'escalations', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_escalations_diagnosis_id'), 'escalations', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_escalations_resolved'), 'escalations', ['resolved'], unique=False)
    op.create_index(op.f('ix_escalations_student_id'), 'escalations', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalations_student_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_resolved'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_diagnosis_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_classroom_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_class_session_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_student_summaries_student_id'), table_name='student_summaries')
    op.drop_index(op.f('ix_student_summaries_experiment_id'), table_name='student_summaries')
    op.drop_index(op.f('ix_student_summaries_classroom_id'), table_name='student_summaries')
    op.drop_index(op.f('ix_student_summaries_class_session_id'), table_name='student_summaries')
    op.drop_table('student_summaries')
    op.drop_index(op.f('ix_socratic_attempts_student_id'), table_name='socratic_attempts')
    op.drop_index(op.f('ix_socratic_attempts_session_id'), table_name='socratic_attempts')
    op.drop_table('socratic_attempts')
    op.drop_index(op.f('ix_diagnoses_tier'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_submission_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_student_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_status'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_classroom_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_class_session_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_chat_messages_student_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_kind'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_experiment_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_classroom_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_class_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_actor_type'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_summary_jobs_status'), table_name='summary_jobs')
    op.drop_index(op.f('ix_summary_jobs_classroom_id'), table_name='summary_jobs')
    op.drop_index(op.f('ix_summary_jobs_class_session_id'), table_name='summary_jobs')
    op.drop_table('summary_jobs')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_experiment_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_classroom_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_class_session_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_actor_type'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_socratic_sessions_student_id'), table_name='socratic_sessions')
    op.drop_index(op.f('ix_socratic_sessions_experiment_id'), table_name='socratic_sessions')
    op.drop_index(op.f('ix_socratic_sessions_classroom_id'), table_name='socratic_sessions')
    op.drop_index(op.f('ix_socratic_sessions_class_session_id'), table_name='socratic_sessions')
    op.drop_index(op.f('ix_socratic_sessions_actor_type'), table_name='socratic_sessions')
    op.drop_table('socratic_sessions')
    op.drop_index(op.f('ix_classroom_memberships_user_id'), table_name='classroom_memberships')
    op.drop_index(op.f('ix_classroom_memberships_role'), table_name='classroom_memberships')
    op.drop_index(op.f('ix_classroom_memberships_classroom_id'), table_name='classroom_memberships')
    op.drop_index(op.f('ix_classroom_memberships_active'), table_name='classroom_memberships')
    op.drop_table('classroom_memberships')
    op.drop_index('uq_one_active_session_per_classroom', table_name='class_sessions', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_class_sessions_status'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_experiment_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_classroom_id'), table_name='class_sessions')
    op.drop_index('ix_class_sessions_active_lookup', table_name='class_sessions')
    op.drop_table('class_sessions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_idem_lookup', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_classrooms_student_join_code'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_faculty_join_code'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_classroom_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_class_session_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
